const LOAD_TRANSLATIONS = 'LOAD_TRANSLATIONS';
const SET_DEFAULT_LANGUAGE = 'SET_DEFAULT_LANGUAGE';
const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
const SET_STYLE_SIDEBAR = 'SET_STYLE_SIDEBAR';

export const ACTION_TYPES = {
  LOAD_TRANSLATIONS,
  SET_DEFAULT_LANGUAGE,
  CHANGE_LANGUAGE,
  OPEN_SIDEBAR,
  CLOSE_SIDEBAR,
  SET_STYLE_SIDEBAR
};
